package com.meroxio.expensemanager;

import android.content.ContentValues;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.Typeface;
import android.graphics.pdf.PdfDocument;
import android.net.Uri;
import android.os.Build;
import android.os.Environment;
import android.provider.MediaStore;
import com.getcapacitor.JSArray;
import com.getcapacitor.JSObject;
import com.getcapacitor.Plugin;
import com.getcapacitor.PluginCall;
import com.getcapacitor.PluginMethod;
import com.getcapacitor.annotation.CapacitorPlugin;
import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStream;
import java.text.NumberFormat;
import java.util.Locale;
import org.json.JSONObject;

@CapacitorPlugin(name = "PdfExport")
public class PdfExportPlugin extends Plugin {
  private static final int PAGE_WIDTH = 595;
  private static final int PAGE_HEIGHT = 842;

  @PluginMethod
  public void save(PluginCall call) {
    getActivity().runOnUiThread(() -> {
      PdfDocument document = new PdfDocument();
      try {
        JSArray rows = call.getArray("rows", new JSArray());
        String currency = call.getString("currency", "INR");
        String fileName = safeFileName(call.getString("fileName", "MeroxIO-Transactions.pdf"));
        drawReport(document, rows, currency);
        String location = writeDocument(document, fileName);
        JSObject result = new JSObject();
        result.put("location", location);
        call.resolve(result);
      } catch (Exception error) {
        call.reject("Could not save PDF: " + error.getMessage(), error);
      } finally {
        document.close();
      }
    });
  }

  private void drawReport(PdfDocument document, JSArray rows, String currency) throws Exception {
    Paint paint = new Paint(Paint.ANTI_ALIAS_FLAG);
    int pageNumber = 1;
    int rowIndex = 0;
    while (rowIndex < Math.max(rows.length(), 1)) {
      PdfDocument.Page page = document.startPage(new PdfDocument.PageInfo.Builder(PAGE_WIDTH, PAGE_HEIGHT, pageNumber++).create());
      Canvas canvas = page.getCanvas();
      canvas.drawColor(Color.WHITE);
      paint.setColor(Color.rgb(15, 23, 42));
      paint.setTypeface(Typeface.create(Typeface.DEFAULT, Typeface.BOLD));
      paint.setTextSize(22);
      canvas.drawText("MeroxIO Expense Manager", 36, 50, paint);
      paint.setTypeface(Typeface.DEFAULT);
      paint.setTextSize(10);
      paint.setColor(Color.rgb(100, 116, 139));
      canvas.drawText("Transaction history", 36, 69, paint);
      int y = 102;
      drawHeader(canvas, paint, y);
      y += 25;
      if (rows.length() == 0) {
        paint.setColor(Color.DKGRAY);
        canvas.drawText("No transactions found.", 36, y + 18, paint);
        rowIndex = 1;
      }
      while (rowIndex < rows.length() && y < PAGE_HEIGHT - 54) {
        JSONObject row = rows.getJSONObject(rowIndex++);
        drawRow(canvas, paint, y, row, currency);
        y += 34;
      }
      paint.setColor(Color.rgb(148, 163, 184));
      paint.setTextSize(9);
      canvas.drawText("Generated by MeroxIO", 36, PAGE_HEIGHT - 24, paint);
      document.finishPage(page);
    }
  }

  private void drawHeader(Canvas canvas, Paint paint, int y) {
    paint.setColor(Color.rgb(241, 245, 249));
    canvas.drawRect(30, y - 17, PAGE_WIDTH - 30, y + 8, paint);
    paint.setColor(Color.rgb(51, 65, 85));
    paint.setTypeface(Typeface.create(Typeface.DEFAULT, Typeface.BOLD));
    paint.setTextSize(9);
    canvas.drawText("DATE", 36, y, paint);
    canvas.drawText("DETAIL", 115, y, paint);
    canvas.drawText("PAYMENT", 365, y, paint);
    canvas.drawText("AMOUNT", 475, y, paint);
    paint.setTypeface(Typeface.DEFAULT);
  }

  private void drawRow(Canvas canvas, Paint paint, int y, JSONObject row, String currency) {
    paint.setTextSize(9);
    paint.setColor(Color.rgb(71, 85, 105));
    canvas.drawText(clip(row.optString("date"), 13), 36, y, paint);
    paint.setColor(Color.rgb(15, 23, 42));
    String detail = row.optString("category") + " - " + row.optString("note", "");
    canvas.drawText(clip(detail, 39), 115, y, paint);
    paint.setColor(Color.rgb(71, 85, 105));
    canvas.drawText(clip(row.optString("paymentMode"), 15), 365, y, paint);
    paint.setColor("income".equals(row.optString("type")) ? Color.rgb(22, 163, 74) : Color.rgb(220, 38, 38));
    canvas.drawText(formatAmount(row.optDouble("amount"), currency), 475, y, paint);
    paint.setColor(Color.rgb(226, 232, 240));
    canvas.drawLine(36, y + 12, PAGE_WIDTH - 36, y + 12, paint);
  }

  private String writeDocument(PdfDocument document, String fileName) throws Exception {
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
      ContentValues values = new ContentValues();
      values.put(MediaStore.Downloads.DISPLAY_NAME, fileName);
      values.put(MediaStore.Downloads.MIME_TYPE, "application/pdf");
      values.put(MediaStore.Downloads.RELATIVE_PATH, Environment.DIRECTORY_DOWNLOADS + "/MeroxIO");
      Uri uri = getContext().getContentResolver().insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI, values);
      if (uri == null) throw new IllegalStateException("Downloads storage is unavailable");
      try (OutputStream output = getContext().getContentResolver().openOutputStream(uri)) {
        document.writeTo(output);
      }
      return "Downloads/MeroxIO/" + fileName;
    }
    File directory = getContext().getExternalFilesDir(Environment.DIRECTORY_DOWNLOADS);
    if (directory == null) throw new IllegalStateException("Device storage is unavailable");
    File file = new File(directory, fileName);
    try (OutputStream output = new FileOutputStream(file)) {
      document.writeTo(output);
    }
    return file.getAbsolutePath();
  }

  private String formatAmount(double amount, String currency) {
    NumberFormat format = NumberFormat.getNumberInstance(new Locale("en", "IN"));
    format.setMaximumFractionDigits(2);
    return ("INR".equals(currency) ? "Rs " : currency + " ") + format.format(amount);
  }

  private String clip(String value, int max) {
    if (value == null) return "";
    return value.length() <= max ? value : value.substring(0, max - 1) + "...";
  }

  private String safeFileName(String value) {
    String clean = value.replaceAll("[^a-zA-Z0-9._-]", "-");
    return clean.toLowerCase(Locale.ROOT).endsWith(".pdf") ? clean : clean + ".pdf";
  }
}
